name: adonixpossystem
description: "Adonix POS System"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  animated_tree_view: ^2.1.0
  fl_chart: ^0.69.0
  flutter_localizations:
    sdk: flutter
  intl: any

cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true # Enables code generation for localization